# Generated by Django 4.1 on 2022-08-18 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0002_customermodel_delete_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customermodel',
            name='customer_id',
        ),
        migrations.AlterField(
            model_name='customermodel',
            name='email',
            field=models.EmailField(max_length=254, primary_key=True, serialize=False),
        ),
    ]
