# Generated by Django 4.1 on 2022-08-18 04:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0003_remove_customermodel_customer_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customermodel',
            name='OrderDate',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
